package org.example.models.enums.items.products;

import org.example.models.enums.items.*;

public enum ProcessedProduct implements Item {
    Honey(Recipe.HoneyRecipe , 75 , 350),
    Cheese(Recipe.CheeseRecipe , 100 , 230),
    LargeCheese(Recipe.LargeCheeseRecipe , 100 , 345),
    GoatCheese(Recipe.GoatCheeseRecipe , 100 , 400),
    LargeGoatCheese(Recipe.LargeGoatCheeseRecipe , 100 , 600),
    Beer(Recipe.BeerRecipe , 50 , 200),
    Vinegar(Recipe.VinegarRecipe , 13 , 100),
    Coffee(Recipe.CoffeeRecipe , 75 , 150),
    AmaranthJuice(Recipe.AmaranthJuiceRecipe , CropType.Amaranth.getEnergy() * 2 ,
            getPriceWithMultiplier(CropType.Amaranth , 2.25)),
    ArtichokeJuice(Recipe.ArtichokeJuiceRecipe , CropType.Artichoke.getEnergy() * 2,
            getPriceWithMultiplier(CropType.Artichoke , 2.25)),
    BeetJuice(Recipe.BeetJuiceRecipe , CropType.Beet.getEnergy() * 2 ,
            getPriceWithMultiplier(CropType.Beet , 2.25)),
    BokChoyJuice(Recipe.BokChoyJuiceRecipe , CropType.BokChoy.getEnergy() * 2 ,
            getPriceWithMultiplier(CropType.BokChoy , 2.25)),
    BroccoliJuice(Recipe.BroccoliJuiceRecipe , CropType.Broccoli.getEnergy() * 2,
            getPriceWithMultiplier(CropType.Broccoli , 2.25)),
    CarrotJuice(Recipe.CarrotJuiceRecipe , CropType.Carrot.getEnergy() * 2,
            getPriceWithMultiplier(CropType.Carrot , 2.25)),
    CauliflowerJuice(Recipe.CauliflowerJuiceRecipe , CropType.Cauliflower.getEnergy() * 2,
            getPriceWithMultiplier(CropType.Cauliflower , 2.25)),
    CornJuice(Recipe.CornJuiceRecipe , CropType.Corn.getEnergy() * 2,
            getPriceWithMultiplier(CropType.Corn , 2.25)),
    EggplantJuice(Recipe.EggplantJuiceRecipe , CropType.Eggplant.getEnergy() * 2,
            getPriceWithMultiplier(CropType.Eggplant , 2.25)),
    FiddleheadFernJuice(Recipe.FiddleheadFernJuiceRecipe , CropType.FiddleheadFern.getEnergy() * 2,
            getPriceWithMultiplier(CropType.FiddleheadFern , 2.25)),
    GarlicJuice(Recipe.GarlicJuiceRecipe , CropType.Garlic.getEnergy() * 2,
            getPriceWithMultiplier(CropType.Garlic , 2.25)),
    GreenBeanJuice(Recipe.GreenBeanJuiceRecipe , CropType.GreenBean.getEnergy() * 2,
            getPriceWithMultiplier(CropType.GreenBean , 2.25)),
    HopsJuice(Recipe.HopsJuiceRecipe , CropType.Hops.getEnergy() * 2,
            getPriceWithMultiplier(CropType.Hops , 2.25)),
    KaleJuice(Recipe.KaleJuiceRecipe , CropType.Kale.getEnergy() * 2 ,
            getPriceWithMultiplier(CropType.Kale , 2.25)),
    ParsnipJuice(Recipe.ParsnipJuiceRecipe , CropType.Parsnip.getEnergy() * 2,
            getPriceWithMultiplier(CropType.Parsnip , 2.25)),
    PotatoJuice(Recipe.PotatoJuiceRecipe , CropType.Potato.getEnergy() * 2,
            getPriceWithMultiplier(CropType.Potato , 2.25)),
    PumpkinJuice(Recipe.PumpkinJuiceRecipe , CropType.Pumpkin.getEnergy() * 2,
            getPriceWithMultiplier(CropType.Pumpkin , 2.25)),
    RadishJuice(Recipe.RadishJuiceRecipe , CropType.Radish.getEnergy() * 2,
            getPriceWithMultiplier(CropType.Radish , 2.25)),
    RedCabbageJuice(Recipe.RedCabbageJuiceRecipe , CropType.RedCabbage.getEnergy() * 2,
            getPriceWithMultiplier(CropType.RedCabbage , 2.25)),
    SummerSquashJuice(Recipe.SummerSquashJuiceRecipe , CropType.SummerSquash.getEnergy() * 2,
            getPriceWithMultiplier(CropType.SummerSquash , 2.25)),
    TomatoJuice(Recipe.TomatoJuiceRecipe , CropType.Tomato.getEnergy() * 2,
            getPriceWithMultiplier(CropType.Tomato , 2.25)),
    UnmilledRiceJuice(Recipe.UnmilledRiceJuiceRecipe , CropType.UnmilledRice.getEnergy() * 2,
            getPriceWithMultiplier(CropType.UnmilledRice , 2.25)),
    WheatJuice(Recipe.WheatJuiceRecipe , CropType.Wheat.getEnergy() * 2,
            getPriceWithMultiplier(CropType.Wheat , 2.25)),
    YamJuice(Recipe.YamJuiceRecipe , CropType.Yam.getEnergy() * 2,
            getPriceWithMultiplier(CropType.Yam , 2.25)),
    Mead(Recipe.MeadRecipe , 100 , 300),
    PaleAle(Recipe.PaleAleRecipe , 50 , 300),
    AncientFruitWine(Recipe.AncientFruitWineRecipe , (int) (CropType.AncientFruit.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.AncientFruit , 3)),
    AppleWine(Recipe.AppleWineRecipe , (int) (FruitType.Apple.getEnergy() * 1.75) ,
            getPriceWithMultiplier(FruitType.Apple , 3)),
    ApricotWine(Recipe.ApricotWineRecipe , (int) (FruitType.Apricot.getEnergy() * 1.75) ,
            getPriceWithMultiplier(FruitType.Apricot , 3)),
    BananaWine(Recipe.BananaWineRecipe , (int) (FruitType.Banana.getEnergy() * 1.75) ,
            getPriceWithMultiplier(FruitType.Banana , 3)),
    BlackberryWine(Recipe.BlackberryWineRecipe , (int) (CropType.Blackberry.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.Blackberry , 3)),
    BlueberryWine(Recipe.BlueberryWineRecipe , (int) (CropType.Blueberry.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.Blueberry , 3)),
    CherryWine(Recipe.CherryWineRecipe , (int) (FruitType.Cherry.getEnergy() * 1.75) ,
            getPriceWithMultiplier(FruitType.Cherry , 3)),
    CranberriesWine(Recipe.CranberriesWineRecipe , (int) (CropType.Cranberry.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.Cranberry , 3)),
    CrystalFruitWine(Recipe.CrystalFruitWineRecipe , (int) (CropType.CrystalFruit.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.CrystalFruit , 3)),
    GrapeWine(Recipe.GrapeWineRecipe , (int) (CropType.Grape.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.Grape , 3)),
    HotPepperWine(Recipe.HotPepperWineRecipe , (int) (CropType.HotPepper.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.HotPepper , 3)),
    MangoWine(Recipe.MangoWineRecipe , (int) (FruitType.Mango.getEnergy() * 1.75) ,
            getPriceWithMultiplier(FruitType.Mango , 3)),
    MelonWine(Recipe.MelonWineRecipe , (int) (CropType.Melon.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.Melon , 3)),
    OrangeWine(Recipe.OrangeWineRecipe , (int) (FruitType.Orange.getEnergy() * 1.75) ,
            getPriceWithMultiplier(FruitType.Orange , 3)),
    PeachWine(Recipe.PeachWineRecipe , (int) (FruitType.Peach.getEnergy() * 1.75) ,
            getPriceWithMultiplier(FruitType.Peach , 3)),
    PomegranateWine(Recipe.PomegranateWineRecipe , (int) (FruitType.Pomegranate.getEnergy() * 1.75) ,
            getPriceWithMultiplier(FruitType.Pomegranate , 3)),
    PowderMelonWine(Recipe.PowderMelonWineRecipe , (int) (CropType.PowderMelon.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.PowderMelon , 3)),
    RhubarbWine(Recipe.RhubarbWineRecipe , (int) (CropType.Rhubarb.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.Rhubarb , 3)),
    SalmonBerryWine(Recipe.SalmonBerryWineRecipe , (int) (CropType.SalmonBerry.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.SalmonBerry, 3)),
    SpiceBerryWine(Recipe.SpiceBerryWineRecipe , (int) (CropType.SpiceBerry.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.SpiceBerry , 3)),
    StarfruitWine(Recipe.StarfruitWineRecipe , (int) (CropType.Starfruit.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.Starfruit , 3)),
    StrawberryWine(Recipe.StrawberryWineRecipe , (int) (CropType.Strawberry.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.Strawberry , 3)),
    WildPlumWine(Recipe.WildPlumWineRecipe , (int) (CropType.WildPlum.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.WildPlum , 3)),
    ChanterelleDriedMushrooms(Recipe.ChanterelleDriedMushroomsRecipe , 50 ,
            getPriceWithMultiplier(CropType.Chanterelle , 7.5) + 25),
    CommonMushroomDriedMushrooms(Recipe.CommonMushroomDriedMushroomsRecipe , 50 ,
            getPriceWithMultiplier(FruitType.CommonMushroom , 7.5) + 25),
    MorelDriedMushrooms(Recipe.MorelDriedMushroomsRecipe , 50 ,
            getPriceWithMultiplier(CropType.Morel , 7.5) + 25),
    PurpleMushroomDriedMushrooms(Recipe.PurpleMushroomDriedMushroomsRecipe , 50 ,
            getPriceWithMultiplier(CropType.PurpleMushroom , 7.5) + 25),
    RedMushroomDriedMushrooms(Recipe.RedMushroomDriedMushroomsRecipe , 50 ,
            getPriceWithMultiplier(CropType.RedMushroom , 7.5) + 25),
    AncientFruitDriedFruit(Recipe.AncientFruitDriedFruitRecipe , 75 ,
            getPriceWithMultiplier(CropType.AncientFruit , 7.5) + 25),
    AppleDriedFruit(Recipe.AppleDriedFruitRecipe , 75 ,
            getPriceWithMultiplier(FruitType.Apple , 7.5) + 25),
    ApricotDriedFruit(Recipe.ApricotDriedFruitRecipe , 75 ,
            getPriceWithMultiplier(FruitType.Apricot , 7.5) + 25),
    BananaDriedFruit(Recipe.BananaDriedFruitRecipe , 75 ,
            getPriceWithMultiplier(FruitType.Banana , 7.5) + 25),
    BlackberryDriedFruit(Recipe.BlackberryDriedFruitRecipe , 75 ,
            getPriceWithMultiplier(CropType.Blackberry , 7.5) + 25),
    BlueberryDriedFruit(Recipe.BlueberryDriedFruitRecipe , 75 ,
            getPriceWithMultiplier(CropType.Blueberry , 7.5) + 25),
    CherryDriedFruit(Recipe.CherryDriedFruitRecipe , 75 ,
            getPriceWithMultiplier(FruitType.Cherry , 7.5) + 25),
    CranberriesDriedFruit(Recipe.CranberriesDriedFruitRecipe , 75 ,
            getPriceWithMultiplier(CropType.Cranberry , 7.5) + 25),
    CrystalFruitDriedFruit(Recipe.CrystalFruitDriedFruitRecipe , 75 ,
            getPriceWithMultiplier(CropType.CrystalFruit , 7.5) + 25),
    HotPepperDriedFruit(Recipe.HotPepperDriedFruitRecipe , 75 ,
            getPriceWithMultiplier(CropType.HotPepper , 7.5) + 25),
    MangoDriedFruit(Recipe.MangoWineRecipe , 75 ,
            getPriceWithMultiplier(FruitType.Mango , 7.5) + 25),
    MelonDriedFruit(Recipe.MelonDriedFruitRecipe , 75 ,
            getPriceWithMultiplier(CropType.Melon , 7.5) + 25),
    OrangeDriedFruit(Recipe.OrangeDriedFruitRecipe , 75 ,
            getPriceWithMultiplier(FruitType.Orange , 7.5) + 25),
    PeachDriedFruit(Recipe.PeachDriedFruitRecipe , 75 ,
            getPriceWithMultiplier(FruitType.Peach , 7.5) + 25),
    PomegranateDriedFruit(Recipe.PomegranateDriedFruitRecipe , 75 ,
            getPriceWithMultiplier(FruitType.Pomegranate , 7.5) + 25),
    PowderMelonDriedFruit(Recipe.PowderMelonDriedFruitRecipe , 75 ,
            getPriceWithMultiplier(CropType.PowderMelon , 7.5) + 25),
    RhubarbDriedFruit(Recipe.RhubarbDriedFruitRecipe , 75 ,
            getPriceWithMultiplier(CropType.Rhubarb , 7.5) + 25),
    SalmonBerryDriedFruit(Recipe.SalmonBerryDriedFruitRecipe , 75 ,
            getPriceWithMultiplier(CropType.SalmonBerry , 7.5) + 25),
    SpiceBerryDriedFruit(Recipe.SpiceBerryDriedFruitRecipe , 75 ,
            getPriceWithMultiplier(CropType.SpiceBerry , 7.5) + 25),
    StarfruitDriedFruit(Recipe.StarfruitDriedFruitRecipe , 75 ,
            getPriceWithMultiplier(CropType.Starfruit , 7.5) + 25),
    StrawberryDriedFruit(Recipe.StrawberryDriedFruitRecipe , 75 ,
            getPriceWithMultiplier(CropType.Strawberry , 7.5) + 25),
    WildPlumDriedFruit(Recipe.WildPlumDriedFruitRecipe , 75 ,
            getPriceWithMultiplier(CropType.WildPlum , 7.5) + 25),
    Raisins(Recipe.RaisinsRecipe , 125 , 600),
    Coal(Recipe.CoalRecipe , 0 , 50),
    Cloth(Recipe.ClothRecipe  , 0 , 470),
    Mayonnaise(Recipe.MayonnaiseRecipe , 50 , 190),
    LargeMayonnaise(Recipe.LargeMayonnaiseRecipe , 50 , 237),
    DuckMayonnaise(Recipe.DuckMayonnaiseRecipe , 75 , 37),
    DinosaurMayonnaise(Recipe.DinosaurMayonnaiseRecipe , 125 , 800),
    Oil(null , 0 , 0),
    TruffleOil(Recipe.TruffleOilRecipe , 38 , 1065),
    CornOil(Recipe.CornOilRecipe , 13 , 100),
    SunflowerSeedOil(Recipe.SunflowerSeedOilRecipe , 10 , 100),
    SunflowerOil(Recipe.SunflowerOilRecipe , 10 , 100),
    AmaranthPickles(Recipe.AmaranthPicklesRecipe , (int) (CropType.Amaranth.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.Amaranth , 2) + 50),
    ArtichokePickles(Recipe.ArtichokePicklesRecipe , (int) (CropType.Artichoke.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.Artichoke , 2) + 50),
    BeetPickles(Recipe.BeetPicklesRecipe , (int) (CropType.Beet.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.Beet , 2) + 50),
    BokChoyPickles(Recipe.BokChoyPicklesRecipe , (int) (CropType.BokChoy.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.BokChoy , 2) + 50),
    BroccoliPickles(Recipe.BroccoliPicklesRecipe , (int) (CropType.Broccoli.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.Broccoli , 2) + 50),
    CarrotPickles(Recipe.CarrotPicklesRecipe , (int) (CropType.Carrot.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.Carrot , 2) + 50),
    CauliflowerPickles(Recipe.CauliflowerPicklesRecipe , (int) (CropType.Cauliflower.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.Cauliflower, 2) + 50),
    CornPickles(Recipe.CornPicklesRecipe , (int) (CropType.Corn.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.Corn , 2) + 50),
    EggplantPickles(Recipe.EggplantPicklesRecipe , (int) (CropType.Eggplant.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.Eggplant , 2) + 50),
    FiddleheadFernPickles(Recipe.FiddleheadFernPicklesRecipe , (int) (CropType.FiddleheadFern.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.FiddleheadFern , 2) + 50),
    GarlicPickles(Recipe.GarlicPicklesRecipe , (int) (CropType.Garlic.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.Garlic , 2) + 50),
    GreenBeanPickles(Recipe.GreenBeanPicklesRecipe , (int) (CropType.GreenBean.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.GreenBean , 2) + 50),
    HopsPickles(Recipe.HopsPicklesRecipe , (int) (CropType.Hops.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.Hops , 2) + 50),
    KalePickles(Recipe.KalePicklesRecipe , (int) (CropType.Kale.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.Kale , 2) + 50),
    ParsnipPickles(Recipe.ParsnipPicklesRecipe , (int) (CropType.Parsnip.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.Parsnip , 2) + 50),
    PotatoPickles(Recipe.PotatoPicklesRecipe , (int) (CropType.Potato.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.Potato , 2) + 50),
    PumpkinPickles(Recipe.PumpkinPicklesRecipe , (int) (CropType.Pumpkin.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.Pumpkin , 2) + 50),
    RadishPickles(Recipe.RadishPicklesRecipe , (int) (CropType.Radish.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.Radish , 2) + 50),
    RedCabbagePickles(Recipe.RedCabbagePicklesRecipe , (int) (CropType.RedCabbage.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.RedCabbage , 2) + 50),
    SummerSquashPickles(Recipe.SummerSquashPicklesRecipe , (int) (CropType.SummerSquash.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.SummerSquash , 2) + 50),
    TomatoPickles(Recipe.TomatoPicklesRecipe , (int) (CropType.Tomato.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.Tomato , 2) + 50),
    UnmilledRicePickles(Recipe.UnmilledRicePicklesRecipe , (int) (CropType.UnmilledRice.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.UnmilledRice , 2) + 50),
    WheatPickles(Recipe.WheatPicklesRecipe , (int) (CropType.Wheat.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.Wheat , 2) + 50),
    YamPickles(Recipe.YamPicklesRecipe , (int) (CropType.Yam.getEnergy() * 1.75) ,
            getPriceWithMultiplier(CropType.Yam , 2) + 50),
    AncientFruitJelly(Recipe.AncientFruitJellyRecipe , CropType.AncientFruit.getEnergy() * 2 ,
            getPriceWithMultiplier(CropType.AncientFruit , 2) + 50),
    AppleJelly(Recipe.AppleJellyRecipe , FruitType.Apple.getEnergy() * 2 ,
            getPriceWithMultiplier(FruitType.Apple , 2) + 50),
    ApricotJelly(Recipe.ApricotJellyRecipe , FruitType.Apricot.getEnergy() * 2,
            getPriceWithMultiplier(FruitType.Apricot , 2) + 50),
    BananaJelly(Recipe.BananaJellyRecipe , FruitType.Banana.getEnergy() * 2,
            getPriceWithMultiplier(FruitType.Banana , 2) + 50),
    BlackberryJelly(Recipe.BlackberryJellyRecipe , CropType.Blackberry.getEnergy() * 2,
            getPriceWithMultiplier(CropType.Blackberry , 2) + 50),
    BlueberryJelly(Recipe.BlueberryJellyRecipe , CropType.Blueberry.getEnergy() * 2 ,
            getPriceWithMultiplier(CropType.Blueberry , 2) + 50),
    CherryJelly(Recipe.CherryJellyRecipe , FruitType.Cherry.getEnergy() * 2,
            getPriceWithMultiplier(FruitType.Cherry , 2) + 50),
    CranberriesJelly(Recipe.CranberriesJellyRecipe , CropType.Cranberry.getEnergy() * 2,
            getPriceWithMultiplier(CropType.Cranberry , 2) + 50),
    CrystalFruitJelly(Recipe.CrystalFruitJellyRecipe , CropType.CrystalFruit.getEnergy() * 2,
            getPriceWithMultiplier(CropType.CrystalFruit , 2) + 50),
    GrapeJelly(Recipe.GrapeJellyRecipe , CropType.Grape.getEnergy() * 2,
            getPriceWithMultiplier(CropType.Grape , 2) + 50),
    HotPepperJelly(Recipe.HotPepperJellyRecipe , CropType.Holly.getEnergy() * 2,
            getPriceWithMultiplier(CropType.HotPepper , 2) + 50),
    MangoJelly(Recipe.MangoJellyRecipe , FruitType.Mango.getEnergy() * 2,
            getPriceWithMultiplier(FruitType.Mango , 2) + 50),
    MelonJelly(Recipe.MelonJellyRecipe , CropType.Melon.getEnergy() * 2,
            getPriceWithMultiplier(CropType.Melon , 2) + 50),
    OrangeJelly(Recipe.OrangeJellyRecipe , FruitType.Orange.getEnergy() * 2,
            getPriceWithMultiplier(FruitType.Orange , 2) + 50),
    PeachJelly(Recipe.PeachJellyRecipe , FruitType.Peach.getEnergy() * 2,
            getPriceWithMultiplier(FruitType.Peach , 2) + 50),
    PomegranateJelly(Recipe.PomegranateJellyRecipe , FruitType.Pomegranate.getEnergy() * 2,
            getPriceWithMultiplier(FruitType.Pomegranate , 2) + 50),
    PowderMelonJelly(Recipe.PowdermelonJellyRecipe , CropType.PowderMelon.getEnergy() * 2,
            getPriceWithMultiplier(CropType.PowderMelon , 2) + 50),
    RhubarbJelly(Recipe.RhubarbJellyRecipe , CropType.Rhubarb.getEnergy() * 2,
            getPriceWithMultiplier(CropType.Rhubarb , 2) + 50),
    SalmonBerryJelly(Recipe.SalmonberryJellyRecipe , CropType.SalmonBerry.getEnergy() * 2,
            getPriceWithMultiplier(CropType.SalmonBerry , 2) + 50),
    SpiceBerryJelly(Recipe.SpiceBerryJellyRecipe , CropType.SpiceBerry.getEnergy() * 2,
            getPriceWithMultiplier(CropType.SpiceBerry , 2) + 50),
    StarfruitJelly(Recipe.StarfruitJellyRecipe , CropType.Starfruit.getEnergy() * 2,
            getPriceWithMultiplier(CropType.Starfruit , 2) + 50),
    StrawberryJelly(Recipe.StrawberryJellyRecipe , CropType.Strawberry.getEnergy() * 2,
            getPriceWithMultiplier(CropType.Strawberry , 2) + 50),
    WildPlumJelly(Recipe.WildPlumJellyRecipe , CropType.WildPlum.getEnergy() * 2,
            getPriceWithMultiplier(CropType.WildPlum , 2) + 50),
    SalmonSmokeFish(Recipe.SalmonSmokeFishRecipe , (int) (FishType.Salmon.getEnergy() * 1.5) ,
            getPriceWithMultiplier(FishType.Salmon , 2)),
    SardineSmokeFish(Recipe.SardineSmokeFishRecipe , (int) (FishType.Sardine.getEnergy() * 1.5),
            getPriceWithMultiplier(FishType.Sardine , 2)),
    ShadSmokeFish(Recipe.ShadSmokeFishRecipe , (int) (FishType.Shad.getEnergy() * 1.5) ,
            getPriceWithMultiplier(FishType.Shad , 2)),
    BlueDiscusSmokeFish(Recipe.BlueDiscusSmokeFishRecipe , (int) (FishType.BlueDiscus.getEnergy() * 1.5) ,
            getPriceWithMultiplier(FishType.BlueDiscus , 2)),
    MidnightCarpSmokeFish(Recipe.MidnightCarpSmokeFishRecipe , (int) (FishType.MidnightCarp.getEnergy() * 1.5) ,
            getPriceWithMultiplier(FishType.MidnightCarp , 2)),
    SquidSmokeFish(Recipe.SquidSmokeFishRecipe , (int) (FishType.Squid.getEnergy() * 1.5) ,
            getPriceWithMultiplier(FishType.Squid , 2)),
    TunaSmokeFish(Recipe.TunaSmokeFishRecipe , (int) (FishType.Tuna.getEnergy() * 1.5) ,
            getPriceWithMultiplier(FishType.Tuna , 2)),
    PerchSmokeFish(Recipe.PerchSmokeFishRecipe , (int) (FishType.Perch.getEnergy() * 1.5) ,
            getPriceWithMultiplier(FishType.Perch , 2)),
    FlounderSmokeFish(Recipe.FlounderSmokeFishRecipe , (int) (FishType.Flounder.getEnergy() * 1.5) ,
            getPriceWithMultiplier(FishType.Flounder , 2)),
    LionfishSmokeFish(Recipe.LionfishSmokeFishRecipe , (int) (FishType.Lionfish.getEnergy() * 1.5),
            getPriceWithMultiplier(FishType.Lionfish , 2)),
    HerringSmokeFish(Recipe.HerringSmokeFishRecipe , (int) (FishType.Herring.getEnergy() * 1.5) ,
            getPriceWithMultiplier(FishType.Herring , 2)),
    GhostfishSmokeFish(Recipe.GhostfishSmokeFishRecipe , (int) (FishType.Ghostfish.getEnergy() * 1.5) ,
            getPriceWithMultiplier(FishType.Ghostfish , 2)),
    TilapiaSmokeFish(Recipe.TilapiaSmokeFishRecipe , (int) (FishType.Tilapia.getEnergy() * 1.5) ,
            getPriceWithMultiplier(FishType.Tilapia , 2)),
    DoradoSmokeFish(Recipe.DoradoSmokeFishRecipe , (int) (FishType.Dorado.getEnergy() * 1.5) ,
            getPriceWithMultiplier(FishType.Dorado , 2)),
    SunfishSmokeFish(Recipe.SunfishSmokeFishRecipe , (int) (FishType.Sunfish.getEnergy() * 1.5) ,
            getPriceWithMultiplier(FishType.Sunfish , 2)),
    RainbowTroutSmokeFish(Recipe.RainbowTroutSmokeFishRecipe , (int) (FishType.RainbowTrout.getEnergy() * 1.5) ,
            getPriceWithMultiplier(FishType.RainbowTrout , 2)),
    LegendSmokeFish(Recipe.LegendSmokeFishRecipe , (int) (FishType.Legend.getEnergy() * 1.5) ,
            getPriceWithMultiplier(FishType.Legend , 2)),
    GlacierfishSmokeFish(Recipe.GlacierfishSmokeFishRecipe , (int) (FishType.Glacierfish.getEnergy() * 1.5),
            getPriceWithMultiplier(FishType.Glacierfish , 2)),
    AnglerSmokeFish(Recipe.AnglerSmokeFishRecipe , (int) (FishType.Angler.getEnergy() * 1.5) ,
            getPriceWithMultiplier(FishType.Angler , 2)),
    CrimsonfishSmokeFish(Recipe.CrimsonfishSmokeFishRecipe , (int) (FishType.Crimsonfish.getEnergy() * 1.5) ,
            getPriceWithMultiplier(FishType.Crimsonfish , 2)),
    CopperMetalBar(Recipe.CopperMetalBarRecipe , 0 , getPriceWithMultiplier(MineralType.CopperOre , 10)),
    IronMetalBar(Recipe.IronMetalBarRecipe , 0 , getPriceWithMultiplier(MineralType.IronOre , 10)),
    GoldMetalBar(Recipe.GoldMetalBarRecipe , 0 , getPriceWithMultiplier(MineralType.GoldOre , 10)),
    IridiumMetalBar(Recipe.IridiumMetalBarRecipe , 0 , getPriceWithMultiplier(MineralType.IridiumOre , 10)),
    Rice(Recipe.RiceRecipe, 0, 250); // energy not defined!

    private final Recipe recipe;
    private final int energy;
    private final int price;

    ProcessedProduct(Recipe recipe, int energy, int price) {
        this.recipe = recipe;
        this.energy = energy;
        this.price = price;
    }

    public Recipe getRecipe() {
        return recipe;
    }

    @Override
    public int getPrice() {
        return price;
    }

    public int getEnergy() {
        return energy;
    }

    private static int getPriceWithMultiplier(Item item , double multiplier) {
        return (int)(item.getPrice() * multiplier);
    }
}
